<?php
$query = <<<SQL
INSERT IGNORE  INTO stg_categorie (libelle) VALUES
('PHP'),
('CSS'),
('JavaScript'),
('HTML'),
('Vue.js 3'),
('Nuxt.js'),
('Next.js'),
('Gatsby'),
('Storybook'),
('JAMstack'),
('Tailwind CSS'),
('Bulma'),
('Materialize'),
('Semantic UI'),
('Foundation'),
('Ant Design'),
('Ionic'),
('Cordova'),
('PhoneGap'),
('Capacitor'),
('RxJS'),
('MobX'),
('Jest'),
('Mocha'),
('Chai'),
('Cypress'),
('Selenium'),
('Appium'),
('Detox'),
('Playwright'),
('Puppeteer'),
('Fastify'),
('NestJS'),
('AdonisJS'),
('LoopBack'),
('Feathers.js'),
('Hapi.js'),
('Socket.IO'),
('Primus'),
('NATS'),
('RabbitMQ'),
('WebSocket'),
('gRPC'),
('GraphQL Yoga'),
('Apollo Server'),
('Apollo Client'),
('Prisma'),
('Sequelize'),
('TypeORM'),
('Knex.js'),
('Beego'),
('Gin'),
('Echo'),
('Buffalo'),
('Chi'),
('Alpine.js'),
('Swiper.js'),
('GSAP'),
('Lottie'),
('Chart.js'),
('Highcharts'),
('D3.js'),
('Mapbox'),
('Leaflet'),
('A-Frame'),
('P5.js'),
('TensorFlow.js'),
('Brain.js'),
('PyTorch'),
('Scikit-Learn'),
('NumPy'),
('Pandas'),
('Matplotlib'),
('Keras'),
('NLTK'),
('Spacy'),
('Beautiful Soup'),
('Puppeteer'),
('Cryptography'),
('OpenSSL'),
('OAuth 2.0'),
('OpenID Connect'),
('JSON Web Tokens'),
('Firebase Auth'),
('Amazon Cognito'),
('Auth0'),
('AWS Lambda'),
('AWS S3'),
('AWS DynamoDB'),
('AWS RDS'),
('AWS EC2'),
('AWS ECS'),
('AWS Lambda'),
('Azure Functions'),
('Azure Blob Storage'),
('Azure Cosmos DB'),
('Azure SQL Database'),
('Google Cloud Functions'),
('Google Cloud Storage'),
('Google Cloud Firestore'),
('Docker Compose'),
('Kubernetes'),
('Jenkins'),
('Travis CI'),
('CircleCI'),
('GitLab CI/CD'),
('GitHub Actions'),
('SonarQube'),
('Git Flow'),
('Feature Toggles'),
('Blue-Green Deployment'),
('Canary Deployment'),
('A/B Testing'),
('Feature Flags'),
('Micro Frontends'),
('Event Sourcing'),
('CQRS'),
('GraphQL Federation'),
('Apollo Federation'),
('RESTful API'),
('SOAP'),
('gRPC'),
('Kafka'),
('RabbitMQ'),
('ActiveMQ'),
('Kotlin Multiplatform'),
('React Native'),
('Flutter'),
('Xamarin'),
('Apache Cordova'),
('Appcelerator Titanium'),
('Adobe PhoneGap'),
('Unity3D'),
('Unreal Engine'),
('Godot Engine'),
('Cocos2d-x'),
('GameMaker Studio'),
('Phaser'),
('HTML5'),
('CSS-in-JS'),
('Styled Components'),
('Emotion'),
('Linaria'),
('CSS Modules'),
('WebAssembly'),
('AssemblyScript'),
('Rust'),
('C/C++'),
('Java'),
('Python'),
('C#'),
('Go'),
('Ruby'),
('Swift'),
('Objective-C'),
('TypeScript'),
('Dart'),
('Kotlin'),
('R'),
('Scala'),
('Haskell'),
('Elixir'),
('Clojure'),
('F#'),
('Lua'),
('Bash/Shell'),
('PowerShell'),
('SQL'),
('NoSQL'),
('Firebase'),
('MongoDB'),
('CouchDB'),
('Redis'),
('Cassandra'),
('Elasticsearch'),
('Neo4j'),
('PostGIS'),
('GraphQL'),
('Apollo Client'),
('Relay'),
('Urql'),
('SWR'),
('React Query'),
('Apollo Server'),
('Prisma'),
('Hasura'),
('GraphQL Yoga'),
('Express GraphQL'),
('AWS AppSync'),
('REST API'),
('JSON API'),
('OpenAPI/Swagger'),
('gRPC'),
('Socket.IO'),
('WebSocket'),
('MQTT'),
('RSocket'),
('AMQP'),
('STOMP'),
('OAuth 2.0'),
('OpenID Connect'),
('JWT'),
('Firebase Auth'),
('Okta'),
('Auth0'),
('Keycloak'),
('AWS Cognito'),
('Azure AD'),
('DevOps'),
('CI/CD'),
('GitOps'),
('Site Reliability Engineering (SRE)'),
('Infrastructure as Code (IaC)'),
('Docker'),
('Kubernetes'),
('OpenShift'),
('Terraform'),
('Ansible'),
('Puppet'),
('Chef'),
('Jenkins'),
('Spinnaker'),
('CircleCI'),
('Travis CI'),
('GitHub Actions'),
('GitLab CI/CD'),
('Distributed Systems'),
('Microservices'),
('Service Mesh (Istio, Linkerd)'),
('API Gateway'),
('Serverless'),
('Event-Driven Architecture'),
('Event Sourcing'),
('CQRS'),
('Domain-Driven Design (DDD)'),
('Hexagonal Architecture'),
('Clean Architecture'),
('Monolith'),
('Containerization'),
('Orchestration'),
('Monitoring'),
('Logging'),
('Tracing'),
('Alerting'),
('Observability'),
('Prometheus'),
('Grafana'),
('ELK Stack'),
('Splunk'),
('New Relic'),
('Datadog'),
('Application Performance Monitoring (APM)'),
('Security'),
('OWASP Top Ten'),
('CORS'),
('CSRF'),
('XSS'),
('XSRF'),
('JWT Security'),
('SSL/TLS'),
('OAuth Security'),
('DevSecOps'),
('Penetration Testing'),
('Compliance (GDPR, HIPAA)'),
('Bug Bounty'),
('Vulnerability Scanning'),
('Security Auditing'),
('Blockchain'),
('Smart Contracts'),
('Decentralized Finance (DeFi)'),
('Consensus Algorithms'),
('Cryptocurrencies'),
('Web3.js'),
('Solidity'),
('Truffle'),
('Ganache'),
('MetaMask'),
('Ethereum'),
('Bitcoin'),
('Hyperledger Fabric'),
('Corda'),
('Quorum'),
('Algorand'),
('Tezos'),
('Polkadot'),
('NFTs'),
('VR (Virtual Reality)'),
('AR (Augmented Reality)'),
('Unity3D'),
('Unreal Engine'),
('A-Frame'),
('Three.js'),
('ARKit'),
('ARCore'),
('Vuforia'),
('IoT (Internet of Things)'),
('Raspberry Pi'),
('Arduino'),
('MQTT'),
('CoAP'),
('Zigbee'),
('LoRaWAN'),
('Node-RED'),
('Edge Computing'),
('5G'),
('Fog Computing'),
('Bluetooth Low Energy (BLE)'),
('RFID'),
('AI (Artificial Intelligence)'),
('Machine Learning'),
('Deep Learning'),
('Natural Language Processing (NLP)'),
('Computer Vision'),
('Reinforcement Learning'),
('Neural Networks'),
('TensorFlow'),
('PyTorch'),
('Keras'),
('Scikit-Learn'),
('XGBoost'),
('Data Science'),
('Data Analysis'),
('Data Visualization'),
('Big Data'),
('Hadoop'),
('Spark'),
('Flink'),
('Kafka'),
('Storm'),
('Cassandra'),
('MongoDB'),
('Couchbase'),
('DynamoDB'),
('Firebase Firestore'),
('Amazon Redshift'),
('Snowflake'),
('Data Warehousing'),
('ETL (Extract, Transform, Load)'),
('SQL'),
('NoSQL'),
('GraphQL'),
('REST API'),
('Postman'),
('Swagger'),
('OpenAPI'),
('RabbitMQ'),
('Apache Kafka'),
('ActiveMQ'),
('NATS'),
('MQTT'),
('GraphQL Subscriptions'),
('WebSockets'),
('Socket.IO'),
('Server-Sent Events (SSE)'),
('Push Notifications'),
('Twilio'),
('Firebase Cloud Messaging (FCM)'),
('OneSignal'),
('AWS Amplify'),
('Pusher'),
('SocketCluster'),
('NestJS'),
('Django Channels'),
('Real-Time Analytics'),
('Elasticsearch'),
('Kibana'),
('Logstash'),
('Loggly'),
('Sumo Logic'),
('Splunk'),
('Graylog'),
('Papertrail'),
('Fluentd'),
('Prometheus'),
('Grafana'),
('Zabbix'),
('Nagios'),
('New Relic'),
('Datadog'),
('AWS CloudWatch'),
('Azure Monitor'),
('Google Cloud Monitoring'),
('Dynatrace'),
('AppDynamics'),
('Pingdom'),
('Uptime Robot'),
('SpeedCurve'),
('Lighthouse'),
('Google PageSpeed Insights'),
('GTmetrix'),
('WebPageTest'),
('YSlow'),
('Performance Budgets'),
('Lazy Loading'),
('Code Splitting'),
('Tree Shaking'),
('Minification'),
('Compression (Gzip, Brotli)'),
('Image Optimization'),
('CDN (Content Delivery Network)'),
('Service Workers'),
('Progressive Web Apps (PWA)'),
('Responsive Design'),
('CSS Grid'),
('Flexbox'),
('CSS Frameworks (Bootstrap, Foundation)'),
('CSS-in-JS'),
('Styled Components'),
('Sass'),
('Less'),
('Stylus'),
('CSS Modules'),
('Tailwind CSS'),
('BEM (Block Element Modifier)'),
('SMACSS (Scalable and Modular Architecture for CSS)'),
('OOCSS (Object-Oriented CSS)'),
('Atomic Design'),
('Design Systems'),
('UI/UX Design'),
('Wireframing'),
('Prototyping'),
('User Research'),
('User Personas'),
('User Flows'),
('Information Architecture'),
('Interaction Design'),
('Mobile-First Design'),
('Responsive Design'),
('Accessibility'),
('Inclusive Design'),
('Color Theory'),
('Typography'),
('Whitespace'),
('Visual Hierarchy'),
('Design Patterns'),
('Material Design'),
('Ant Design'),
('iOS Human Interface Guidelines'),
('Google Material Guidelines'),
('Atomic Design'),
('BEM (Block Element Modifier)'),
('SMACSS (Scalable and Modular Architecture for CSS)'),
('OOCSS (Object-Oriented CSS)'),
('Progressive Enhancement'),
('Mobile-First Design'),
('Responsive Web Design'),
('Cross-Browser Compatibility'),
('Web Performance Optimization'),
('Critical Rendering Path'),
('Page Load Time'),
('Time to First Byte (TTFB)'),
('Render-Blocking Resources'),
('Optimize Images'),
('Minify CSS, JS, HTML'),
('Gzip Compression'),
('Brotli Compression'),
('Caching'),
('Browser Caching'),
('CDN (Content Delivery Network)'),
('Service Workers'),
('Lazy Loading'),
('Code Splitting'),
('Tree Shaking'),
('Progressive Web Apps (PWA)'),
('WebAssembly'),
('Rust'),
('AssemblyScript'),
('Emscripten'),
('WebRTC'),
('WebSockets'),
('gRPC Web'),
('HTTP/2'),
('HTTP/3'),
('Server Push'),
('Browsers'),
('Google Chrome'),
('Mozilla Firefox'),
('Safari'),
('Microsoft Edge'),
('Opera'),
('Internet Explorer'),
('Cross-Browser Testing'),
('Browser DevTools'),
('Google Chrome DevTools'),
('Firefox Developer Tools'),
('Safari Web Inspector'),
('Microsoft Edge DevTools'),
('Opera Developer Tools'),
('Internet Explorer F12 Developer Tools'),
('Version Control'),
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('Git Flow'),
('Semantic Versioning'),
('Changelog'),
('Branching Strategies'),
('Feature Branches'),
('Release Branches'),
('Hotfix Branches'),
('Pull Requests'),
('Merge Conflicts'),
('Continuous Integration (CI)'),
('Travis CI'),
('Jenkins'),
('CircleCI'),
('GitLab CI'),
('GitHub Actions'),
('TeamCity'),
('Build Automation'),
('Code Quality'),
('Code Review'),
('Static Code Analysis'),
('Code Linters'),
('Code Formatters'),
('SonarQube'),
('Test Automation'),
('Unit Testing'),
('Integration Testing'),
('End-to-End Testing'),
('Test Frameworks'),
('Jest'),
('Mocha'),
('Chai'),
('Cypress'),
('Selenium'),
('TestCafe'),
('Appium'),
('Detox'),
('Mocking'),
('Sinon.js'),
('Nock'),
('Mockito'),
('Jasmine'),
('Testing Library'),
('Storybook'),
('Snapshot Testing'),
('Mutation Testing'),
('Load Testing'),
('Apache JMeter'),
('LoadRunner'),
('K6'),
('Locust'),
('Gatling'),
('Performance Monitoring'),
('New Relic'),
('Datadog'),
('AppDynamics'),
('Dynatrace'),
('SolarWinds'),
('Scalyr'),
('Application Insights'),
('PagerDuty'),
('Logging'),
('Centralized Logging'),
('Elasticsearch'),
('Logstash'),
('Kibana'),
('Splunk'),
('Graylog'),
('Loggly'),
('Papertrail'),
('Fluentd'),
('Logging Libraries'),
('Winston'),
('Bunyan'),
('Log4j'),
('SLF4J'),
('Serilog'),
('Cloud-Native Logging'),
('Distributed Tracing'),
('OpenTelemetry'),
('Jaeger'),
('Zipkin'),
('AWS X-Ray'),
('Dapper'),
('APM (Application Performance Monitoring)'),
('Full-Stack Tracing'),
('Error Monitoring'),
('Sentry'),
('Rollbar'),
('Bugsnag'),
('Airbrake'),
('Raygun'),
('Exception Handling'),
('Crash Reporting'),
('Firebase Crashlytics'),
('Instabug'),
('Quality Assurance (QA)'),
('Manual Testing'),
('Automated Testing'),
('Regression Testing'),
('User Acceptance Testing (UAT)'),
('Smoke Testing'),
('Performance Testing'),
('Security Testing'),
('Penetration Testing'),
('Load Testing'),
('Usability Testing'),
('Compatibility Testing'),
('Accessibility Testing'),
('A/B Testing'),
('Test Case Management'),
('TestRail'),
('Zephyr'),
('qTest'),
('Test Execution'),
('Continuous Testing'),
('Shift-Left Testing'),
('Shift-Right Testing'),
('Shift-Down Testing'),
('Agile Testing'),
('Behavior-Driven Development (BDD)'),
('Gherkin'),
('Cucumber'),
('SpecFlow'),
('Robot Framework'),
('Given-When-Then'),
('TDD (Test-Driven Development)'),
('Red-Green-Refactor'),
('Unit Testing'),
('Mocking'),
('Code Coverage'),
('Continuous Integration'),
('Continuous Delivery'),
('Continuous Deployment'),
('Continuous Monitoring'),
('Feature Toggles'),
('Feature Flags'),
('Rolling Deployment'),
('Canary Deployment'),
('Blue-Green Deployment'),
('Dark Launching'),
('Experimentation'),
('A/B Testing'),
('Multivariate Testing'),
('Feature Experimentation'),
('Split Testing'),
('Conversion Rate Optimization (CRO)'),
('Funnel Analysis'),
('User Analytics'),
('Event Tracking'),
('Google Analytics'),
('Mixpanel'),
('Amplitude'),
('Heap Analytics'),
('Crazy Egg'),
('Hotjar'),
('FullStory'),
('Segment'),
('Optimizely');



SQL;

echo $query;