<?php

$query = <<<SQL

DROP TABLE IF EXISTS table_temporaire ;
CREATE TABLE table_temporaire(
    id_table INT,
    Numero_Convention INT,
    Numero_etudiant VARCHAR(256),
    Nom_etudiant VARCHAR(256),
    Prenom_etudiant VARCHAR(256),
    Telephone_Perso_etudiant VARCHAR(20),
    Telephone_Portable_etudiant VARCHAR(20),
    Mail_Perso_etudiant VARCHAR(320),
    Mail_Universitaire_etudiant VARCHAR(320),
    Code_Ufr VARCHAR(4),
    Libelle_UFR VARCHAR(256),
    Code_departement VARCHAR(32),
    Code_etape VARCHAR(64),
    Libelle_Etape VARCHAR(256),
    Date_Debut_Stage VARCHAR(256),
    Date_Fin_Stage VARCHAR(256),
    Interruption VARCHAR(32),
    Date_Debut_Interruption VARCHAR(256),
    Date_Fin_Interruption VARCHAR(256),
    Thematique VARCHAR(256),
    Sujet VARCHAR(256),
    Fonctions_et_Taches BLOB,
    Detail_du_Projet BLOB,
    Duree_du_Stage BLOB,
    Nb_de_jours_de_travail INT,
    Nombre_d_heures_hebdomadaire INT,
    Gratification DECIMAL(15, 2),
    Unite_Gratification VARCHAR(4),
    Unite_Duree_Gratification VARCHAR(256),
    Convention_Validee VARCHAR(256),
    Nom_Enseignant_referent VARCHAR(256),
    Prenom_Enseignant_referent VARCHAR(256),
    Mail_Enseignant_referent VARCHAR(320),
    Nom_Signataire VARCHAR(256),
    Prenom_Signataire VARCHAR(256),
    Mail_Signataire VARCHAR(320),
    Fonction_Signataire VARCHAR(256),
    Annee_Universitaire VARCHAR(256),
    Type_de_Convention VARCHAR(256),
    Commentaire_Stage VARCHAR(1024),
    Commentaire_Duree_Travail BLOB,
    Code_ELP VARCHAR(256),
    Element_pedagogique VARCHAR(256),
    Code_sexe_etudiant VARCHAR(1),
    Avantages_nature VARCHAR(256),
    Adresse_etudiant VARCHAR(256),
    Code_postal_etudiant VARCHAR(50),
    Pays_etudiant VARCHAR(256),
    Ville_etudiant VARCHAR(256),
    Con_Vali_Peda VARCHAR(32),
    Avenant_a_la_convention VARCHAR(32),
    Details_Avenant VARCHAR(256),
    Date_creation_conv VARCHAR(256),
    Date_modi_conv VARCHAR(256),
    Origine_stage VARCHAR(256),
    Nom_Etablissement_d_accueil VARCHAR(256),
    Siret VARCHAR(14),
    Adresse_Residence VARCHAR(256),
    Adresse_Voie VARCHAR(256),
    Adresse_lib_cedex VARCHAR(256),
    Code_Postal VARCHAR(50),
    Eta_Accueil_Com VARCHAR(256),
    Pays VARCHAR(256),
    Statut_Juridique VARCHAR(256),
    Type_de_Structure VARCHAR(256),
    Effectif VARCHAR(32),
    Code_NAF VARCHAR(256),
    Telephone VARCHAR(20),
    Fax VARCHAR(20),
    Mail_Structure VARCHAR(320),
    SiteWeb VARCHAR(256),
    Service_d_accueil_Nom VARCHAR(256),
    Service_d_accueil_Residence VARCHAR(256),
    Service_d_accueil_Voie VARCHAR(256),
    Service_d_accueil_Cedex VARCHAR(256),
    Service_d_accueil_Code_postal VARCHAR(50),
    Service_d_accueil_Commune VARCHAR(50),
    Service_d_accueil_Pays VARCHAR(256),
    Nom_Tuteur_Professionnel VARCHAR(256),
    Prenom_Tuteur_Professionnel VARCHAR(256),
    Mail_Tuteur_professionnel VARCHAR(320),
    Telephone_Tuteur_Professionnel VARCHAR(20),
    Fonction_Tuteur_Professionnel VARCHAR(256)
);

SQL;
echo $query;